"""
Gate 0 invariants — locked against the captured replay corpus.

Every v4.0 desktop pivot phase MUST keep these tests green. They lock the
three mathematical contracts the v3.4 → v4.0 transport rewrite cannot
break:

  1. Deterministic segment identity:
        segment_id = SHA256(uuid(session_id) | start_iso | end_iso)
     Re-derives each captured fixture's ``segment_id`` from its
     ``session_id`` and window bounds and asserts equality.

  2. §7B reward path:
        r_t = P90(bounded AU12 in [t_stim+0.5, t_stim+5.0]) × G_t
     Replays each fixture's AU12 series and ``_stimulus_time`` through
     the canonical ``compute_reward`` and asserts the gated reward
     matches the locked float baseline below to 12 decimal places.

  3. Fractional Beta-Bernoulli posterior update:
        α' = α + r,   β' = β + (1 - r)
     Locked as a pure-math contract — no MetricsStore required.

The captured fixtures live in ``tests/fixtures/v4_gate0/`` and were
generated by the v3.4 Docker stack before dependency management was
consolidated into ``pyproject.toml`` and ``uv.lock``. The raw inputs that
produced them are tracked at
``tests/fixtures/capture/baseline/{audio.wav,video.mkv,stimulus_script.json}``.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import TypedDict

import pytest

from packages.schemas.inference_handoff import InferenceHandoffPayload
from services.worker.pipeline.reward import TimestampedAU12, compute_reward


class _Au12Obs(TypedDict):
    timestamp_s: float
    intensity: float


class _Fixture(TypedDict):
    session_id: str
    segment_id: str
    segment_window_start_utc: str
    segment_window_end_utc: str
    _stimulus_modality: str
    _stimulus_payload: dict[str, object]
    _expected_stimulus_rule: str
    _expected_response_rule: str
    _stimulus_time: float
    _au12_series: list[_Au12Obs]
    _bandit_decision_snapshot: dict[str, object]


GATE0_FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "v4_gate0"

# Locked reward baselines derived from the captured fixtures by a one-shot
# replay through services.worker.pipeline.reward.compute_reward. Any drift
# here means a v4 phase has altered the §7B reward semantics — fix the
# regression, do not adjust the baseline.
EXPECTED_REWARDS: dict[str, dict[str, float | int]] = {
    "7e6e76fcddb03419cfd060af41ab0cb7ce9b859ce6ae1c192f0b1c4892fafe2c": {
        "p90_intensity": 0.8064131156,
        "gated_reward": 0.8064131156,
        "n_frames_in_window": 52,
    },
    "b62faa57503b5d6283f5854dc05746df2b3312125bc79cf00da3c04b5d4c4447": {
        "p90_intensity": 0.8417927648,
        "gated_reward": 0.8417927648,
        "n_frames_in_window": 52,
    },
    "cf1700391ee660ff4eb3b219b515b9ce25d4312ed387dc75376043b144d7cf5e": {
        "p90_intensity": 0.8166551813,
        "gated_reward": 0.8166551813,
        "n_frames_in_window": 52,
    },
}


def _canonical_utc_timestamp(value: str) -> str:
    """Re-implement the orchestrator's canonical UTC formatter for parity."""
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    return parsed.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _load_fixtures() -> list[_Fixture]:
    fixtures: list[_Fixture] = []
    for path in sorted(GATE0_FIXTURE_DIR.glob("segment_*.json")):
        fixtures.append(json.loads(path.read_text()))
    return fixtures


def _fixture_ids() -> list[str]:
    paths = sorted(GATE0_FIXTURE_DIR.glob("segment_*.json"))
    return [p.stem.removeprefix("segment_") for p in paths]


@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_segment_id_derives_from_stable_identity(fixture: _Fixture) -> None:
    """SHA256(uuid|start|end) — drift here breaks Module C ↔ Module D handoff."""
    stable_identity = "|".join(
        (
            f"{uuid.UUID(fixture['session_id'])}",
            _canonical_utc_timestamp(fixture["segment_window_start_utc"]),
            _canonical_utc_timestamp(fixture["segment_window_end_utc"]),
        )
    )
    expected = hashlib.sha256(stable_identity.encode("utf-8")).hexdigest()
    assert fixture["segment_id"] == expected


@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_gate0_fixture_validates_against_handoff_schema(fixture: _Fixture) -> None:
    handoff_data = dict(fixture)
    handoff_data.pop("_experiment_code", None)
    payload = InferenceHandoffPayload.model_validate(handoff_data)
    snapshot = payload.bandit_decision_snapshot

    assert payload.stimulus_modality == fixture["_stimulus_modality"]
    assert payload.stimulus_payload.model_dump() == fixture["_stimulus_payload"]
    assert payload.expected_stimulus_rule == fixture["_expected_stimulus_rule"]
    assert payload.expected_response_rule == fixture["_expected_response_rule"]
    assert "_expected_greeting" not in fixture
    assert "expected_greeting" not in fixture["_bandit_decision_snapshot"]
    assert snapshot.decision_context_hash
    assert isinstance(snapshot.random_seed, int)
    assert snapshot.expected_stimulus_rule
    assert snapshot.expected_response_rule
    assert snapshot.stimulus_payload.text


@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_reward_math_replays_to_locked_baseline(fixture: _Fixture) -> None:
    """§7B reward path — drift here invalidates every prior posterior update."""
    series = [
        TimestampedAU12(timestamp_s=obs["timestamp_s"], intensity=obs["intensity"])
        for obs in fixture["_au12_series"]
    ]
    result = compute_reward(
        au12_series=series,
        stimulus_time_s=fixture["_stimulus_time"],
        is_match=True,
    )

    expected = EXPECTED_REWARDS[fixture["segment_id"]]
    assert result.semantic_gate == 1
    assert result.n_frames_in_window == expected["n_frames_in_window"]
    assert result.p90_intensity == pytest.approx(expected["p90_intensity"], abs=1e-10)
    assert result.gated_reward == pytest.approx(expected["gated_reward"], abs=1e-10)


@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_semantic_gate_zeroes_reward(fixture: _Fixture) -> None:
    """G_t=0 must crush the gated reward to 0 even with high P90."""
    series = [
        TimestampedAU12(timestamp_s=obs["timestamp_s"], intensity=obs["intensity"])
        for obs in fixture["_au12_series"]
    ]
    result = compute_reward(
        au12_series=series,
        stimulus_time_s=fixture["_stimulus_time"],
        is_match=False,
    )
    assert result.semantic_gate == 0
    assert result.gated_reward == 0.0
    assert result.p90_intensity > 0.0


def test_fractional_beta_bernoulli_update() -> None:
    """α' = α + r, β' = β + (1 - r) — pure math contract, no store required."""
    alpha, beta = 1.0, 1.0
    reward = 0.8166551813
    new_alpha = alpha + reward
    new_beta = beta + (1.0 - reward)

    assert new_alpha == pytest.approx(1.8166551813, abs=1e-12)
    assert new_beta == pytest.approx(1.1833448187, abs=1e-12)
    # Posterior mass is conserved: α' + β' = α + β + 1 for any reward in [0,1].
    assert (new_alpha + new_beta) == pytest.approx(alpha + beta + 1.0, abs=1e-12)


@pytest.mark.parametrize("reward", [0.0, 1.0])
def test_fractional_update_at_bounds(reward: float) -> None:
    """At r=0 only β advances; at r=1 only α advances."""
    alpha, beta = 1.0, 1.0
    new_alpha = alpha + reward
    new_beta = beta + (1.0 - reward)
    if reward == 0.0:
        assert new_alpha == 1.0
        assert new_beta == 2.0
    else:
        assert new_alpha == 2.0
        assert new_beta == 1.0
