"""Static regression guard for merge-conflict artifacts.

The post-merge cleanup must catch both raw Git conflict markers and the
Azure DevOps conflict-extension separator lines that are easy to miss in
large Python files. The test only scans text-like repository files and
skips virtualenvs, caches, node modules, and generated/binary fixture
locations so it remains fast and deterministic.
"""

from __future__ import annotations

from pathlib import Path

_TEXT_SUFFIXES = {
    ".py",
    ".md",
    ".yaml",
    ".yml",
    ".json",
    ".toml",
    ".ini",
    ".txt",
    ".sh",
}

_EXCLUDED_DIRS = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "node_modules",
    "build",
    "dist",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    "htmlcov",
    ".coverage",
}

_GENERATED_OR_BINARY_DIRS = {
    "data-raw",
    "data-interim",
    "data-processed",
    "artifacts",
}

_RAW_START_MARKERS = (
    "<" * 7,
    ">" * 7,
    "|" * 7,
)
_RAW_SEPARATOR_MARKER = "=" * 7
_EXTENSION_TOKEN = "AUTO GENERATED BY " + "CONFLICT EXTENSION"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _should_skip(path: Path, root: Path) -> bool:
    relative_parts = path.relative_to(root).parts
    if any(part in _EXCLUDED_DIRS for part in relative_parts):
        return True
    if any(part in _GENERATED_OR_BINARY_DIRS for part in relative_parts):
        return True
    return path.suffix.lower() not in _TEXT_SUFFIXES


def _offending_lines(path: Path) -> list[tuple[int, str]]:
    offenders: list[tuple[int, str]] = []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError:
        return offenders

    for lineno, line in enumerate(lines, start=1):
        stripped = line.strip()
        if _EXTENSION_TOKEN in line:
            offenders.append((lineno, line))
            continue
        if any(stripped.startswith(marker) for marker in _RAW_START_MARKERS):
            offenders.append((lineno, line))
            continue
        if stripped == _RAW_SEPARATOR_MARKER:
            offenders.append((lineno, line))
    return offenders


def test_repository_text_files_do_not_contain_merge_conflict_artifacts() -> None:
    root = _repo_root()
    failures: list[str] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or _should_skip(path, root):
            continue
        for lineno, line in _offending_lines(path):
            rel = path.relative_to(root)
            failures.append(f"{rel}:{lineno}: {line}")

    assert failures == []
